project: 
  type: website          
  output-dir: docs    
  
website:
  title: "Dana Bauer"
  favicon: "/imagenes/J.png"
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: "./imagenes/J.png"
    background: "#000000"
    foreground: "#FFFFFF"
    right:
      - text: "Portafolio"
        href: Portafolio.qmd
      - text: "About"
        href: About.qmd
  page-footer:
    border: true
    background: "#000000"
    left: "© Dana Bauer"
    right:
      - icon: tiktok
        href: https://www.tiktok.com/@danabauerr/
      - icon: instagram
        href: https://www.instagram.com/danabauerrm/
format:
  html:
    theme: journal
    mainfont: Bebas Neue
    highlight-style: a11y
    css: my_styles.css
    page-layout: full
    toc: true
    toc-location: right
    toc-title: "Índice"
    code-copy: true
    code-overflow: wrap
    code-fold: show
    code-line-numbers: true

# Enable CC licence appendix
#license: "CC BY"

lang: es  

# Default execute options
execute:
  echo: false
  message: false
  warning: false
  eval: true
  #fig-align: center
  #freeze: true  #- des-comentar cuando estéis tuneando el blog
                 #- https://quarto.org/docs/projects/code-execution.html#freeze
    

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999)  
